services:
  database:
    container_name: postgres
    image: postgres:17.5-alpine3.22
    network_mode: host
    command: postgres -c 'max_connections=450'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  cache:
    container_name: cache
    image: redis:8.0.3-alpine3.21
    network_mode: host
    volumes:
      - ./data/redis:/data

  api1: &api
    container_name: api1
    image: alvesluis0/scalable-shortener:latest
    network_mode: host
    command: ["bin/rails", "server", "-p", "3001"]
    environment:
      HOST: localhost
      PORT: 3000
      SHORT_CODE_SALT: 1e92b4e6ae973a0755052f260fbeed33bb6f1827b442573bd5ebd2a7a4d9af5ed29428e500477b1685caeaeaa4927e1262bd447fbf6a93fe9a38cffea1945699
      SECRET_KEY_BASE: 381c390dd9ab945381cd7a78fc62a1eb65ee51116d799edc85301c8bb4aaa44ab6f4ac31f5c660139b1f1c523cec9fd8ed771e3a32cf4e2a084263ce1815be4f
    depends_on:
      - database
      - cache

  api2:
    <<: *api
    container_name: api2
    command: ["bin/rails", "server", "-p", "3002"]
    environment:
      HOST: localhost
      PORT: 3000
      SHORT_CODE_SALT: 1e92b4e6ae973a0755052f260fbeed33bb6f1827b442573bd5ebd2a7a4d9af5ed29428e500477b1685caeaeaa4927e1262bd447fbf6a93fe9a38cffea1945699
      SECRET_KEY_BASE: 381c390dd9ab945381cd7a78fc62a1eb65ee51116d799edc85301c8bb4aaa44ab6f4ac31f5c660139b1f1c523cec9fd8ed771e3a32cf4e2a084263ce1815be4f
    depends_on:
      - database
      - cache
      - api1

  loadbalancer:
    container_name: loadbalancer
    image: nginx:1.29.1-alpine3.22
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2