require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/urls", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Url. As you add validations to Url, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { original_url: "https://www.google.com/" }
  }

  let(:invalid_attributes) {
    { original_url: "" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # UrlsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Url" do
        expect {
          post urls_url,
               params: { url: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Url, :count).by(1)
      end

      it "renders a JSON response with the new url" do
        post urls_url,
             params: { url: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Url" do
        expect {
          post urls_url,
               params: { url: invalid_attributes }, as: :json
        }.to change(Url, :count).by(0)
      end

      it "renders a JSON response with errors for the new url" do
        post urls_url,
             params: { url: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "GET /:short_code" do
    context "with valid parameters" do
      it "redirects to the original url" do
        id = (Url.maximum(:id) || 0) + 1
        short_code = GenerateShortCodeService.new(id).call
        url = Url.create!(valid_attributes.merge(short_code: short_code))
        get short_redirect_url(short_code: url.short_code), headers: valid_headers, as: :json
        expect(response).to redirect_to(url.original_url)
      end
    end
  end
end
